import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Home.module.css";

export default function Login() {

  async function Signin() {
    e.preventDefault();
    let headers = new Headers();

    headers.append("Content-Type", "application/json");
    headers.append("Accept", "application/json");
    // headers.append('Authorization', 'Basic ' + base64.encode(username + ":" +  password));
    headers.append("Origin", "http://localhost:3000");

    // console.log(userInput)
    const res = await fetch("http://localhost:3000/auth/signup/company", {
      mode: "cors",
      credentials: "include",
      method: "POST",
      headers: headers,
      body: JSON.stringify(userInput),
    }).then((response) => response.json())
      .then (company => {
        setCompanyData({...companyData, company})
      });
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.signIn}>
            <div className={styles.logo}>
              <Image
                src="/EasyHandler_Putih.png"
                alt="logo"
                width={200}
                height={200}
              />
            </div>
            <h2>Login To Your Account</h2>
            <div className={styles.formLogin}>
              <label>Company Email</label>
              <input name="email" type="email"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Password</label>
              <input name="password" type="password" ></input>
            </div>
            <Link href="/Registration/forgot">
              <a className={styles.forgot}>Forgot Password?</a>
            </Link>
            <Link href="#">
              <a className={styles.butSignin}>Sign In</a>
            </Link>
          </div>
          <div className={styles.signUp}>
            <h1>New Here?</h1>
            <p>Sign up and discover a great amount of new opportunities</p>
            <Link href="/Registration/signUp">
              <a className={styles.butSignup}>Sign Up</a>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
