import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Dashboard.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
	faA,
	faBuilding,
	faCaretRight,
	faCircleInfo,
	faMoneyBillTransfer,
	faSignal,
	faUserPlus,
	faEllipsisVertical,
} from "@fortawesome/free-solid-svg-icons";
import Navbar from "./Component/navbar"
import { useState } from "react";

export default function Dashboard({user}) {
	console.log(user, "q")
	const [userInput,setUserInput] = useState(user);
	async function test(e){

		let headers = new Headers();

		headers.append("Content-Type", "application/json");
		headers.append("Accept", "application/json");
		// headers.append('Authorization', 'Basic ' + base64.encode(username + ":" +  password));
		headers.append("Origin", "http://localhost:3000");
		headers.append("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmZiNWY4MGYxMmE3ZDNiYTc2M2QzYjAiLCJlbWFpbCI6ImhlbmRyaXlhbnRvNzI1QGdtYWlsLmNvbSIsImNvbXBhbnkiOiI2MmZiNDZlNjdhOWE0ZDllMWM0NDgwYzciLCJpYXQiOjE2Njk3MDk3MjAsImV4cCI6MTY2OTcyNzcyMH0.QG7s3qeCakyXcK6fh0Lg-30eOKY426TL6hgBtU63LKg")
	
	
		// const res = await 
		const res = await fetch("http://localhost:3000/users/myprofile", {
		  mode: "cors",
		  credentials: "include",
		  method: "GET",
		  headers: headers,
		})
		const w = await res.json().then(user => {return user})

		return" asw"
		// console.log(x.json().)
		// console.log(x.Object)
		// console.log(x.result)
	}

	return (
		<div className={styles.container}>
			<button onClick={test}>
				test
			</button>

			<Head>
				<title>Company Name</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Navbar />
				<div className={`${styles.container}`}>
					<div className={`${styles["head-card"]} card`}>
						<div className={`${styles["head-card-body"]} card-body`}>
							<div className={`d-flex justify-content-between`}>
								<div>
									<h3 class="fw-bold">PT Hexaon Business Mitrasindo</h3>
									<div className={`ms-5 fw-bold`}>
										<h6 class="card-text fw-bold">good afternoon, ester!</h6>
										<p class="card-text">it's thursday 19 may 2022</p>
									</div>
								</div>
								<img
									src="/clerical-staff.png"
									className={`${styles["img-head-card"]} me-5`}
								/>
							</div>
							<div className={`${styles["button-head"]} fw-bold`}>
								<h5 class="my-3 ms-4 fw-bold">Shortcut</h5>
								<ul>
									<li className={`me-5`}>
										<a href="#">Live Attendance</a>
									</li>
									<li className={`mx-5`}>
										<a href="#">Request Reimbursement</a>
									</li>
									<li className={`mx-5`}>
										<a href="#">Request Time Off</a>
									</li>
									<li className={`ms-5`}>
										<a href="#">More Request</a>
									</li>
								</ul>
							</div>
						</div>
					</div>

					<div
						className={`${styles["body-card"]} d-flex justify-content-between mx-3`}
					>
						<div className={`${styles["card-row-one"]}`}>
							<div class="card mb-2">
								<div class="card-body">
									<div
										className={`${styles["card-title"]} d-flex justify-content-between`}
									>
										<h3 class="card-title">Employment Status</h3>
										<FontAwesomeIcon icon={faEllipsisVertical} />
									</div>
									<div className={`${styles["progress-bar"]} progress`}>
										<div
											className={`${styles["progress1"]} progress-bar`}
											role="progressbar"
											aria-label="Segment one"
											aria-valuenow="15"
											aria-valuemin="0"
											aria-valuemax="100"
										></div>
										<div
											className={`${styles["progress2"]} progress-bar`}
											role="progressbar"
											aria-label="Segment two"
											aria-valuenow="30"
											aria-valuemin="0"
											aria-valuemax="100"
										></div>
										<div
											className={`${styles["progress3"]} progress-bar`}
											role="progressbar"
											aria-label="Segment three"
											aria-valuenow="20"
											aria-valuemin="0"
											aria-valuemax="100"
										></div>
									</div>
								</div>
							</div>
							<div class="card">
								<div class="card-body">
									<div
										className={`${styles["card-title"]} d-flex justify-content-between`}
									>
										<h3 class="card-title">Gender Diversity</h3>
										<FontAwesomeIcon icon={faEllipsisVertical} />
									</div>
									<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
									<p class="card-text">
										Some quick example text to build on the card title and make up the
										bulk of the card's content.
									</p>
									<a href="#" class="card-link">
										Card link
									</a>
									<a href="#" class="card-link">
										Another link
									</a>
								</div>
							</div>
						</div>

						<div className={`${styles["card-row-two"]}`}>
							<div className={`${styles["card-1"]} card mb-2`}>
								<div className={`${styles["card-1-header"]} border-bottom`}>
									<ul className={``}>
										<Link href="#">
											<li className={`me-4 mt-3`}>
												<a>Announcement</a>
											</li>
										</Link>
										<Link href="#">
											<li className={`me-4 mt-3`}>
												<a>Contract & Probation</a>
											</li>
										</Link> 
										<Link href="#">
											<li className={`me-4 mt-3`}>
												<a>Tasks</a>
											</li>
										</Link>
										<Link href="#">
											<li className={`me-4 mt-3`}>
												<a>Polings</a>
											</li>
										</Link>
									</ul>
								</div>
								<div class="card-body d-flex justify-content-start">
									<Image src="/group3.png" width={50} height={50} />
									<p class="mt-2 ms-3">What do you want to announce</p>
								</div>
							</div>
							<div class="card mb-2">
								<div class="card-body">
									<h3 class="card-title">Card title</h3>
									<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
									<p class="card-text">
										Some quick example text to build on the card title and make up the
										bulk of the card's content.
									</p>
									<a href="#" class="card-link">
										Card link
									</a>
									<a href="#" class="card-link">
										Another link
									</a>
								</div>
							</div>
							<div class="card mb-2">
								<div
									className={`${styles["card-3-body"]} card-body d-flex justify-content-between`}
								>
									<div className={styles.quickl}>
										<h5 className={`border-bottom`}>Quick Link</h5>
										<ul>
											<li>
												<a href="#">
													<FontAwesomeIcon
														className={styles.icon}
														icon={faCircleInfo}
														styles={{ fontSize: "10", color: "black" }}
													/>
													My Info
												</a>
											</li>
											<li>
												<a href="#">
													<FontAwesomeIcon
														className={styles.icon}
														icon={faUserPlus}
														styles={{ fontSize: "10", color: "black" }}
													/>
													Add Employee
												</a>
											</li>
											<li>
												<a href="#">
													<FontAwesomeIcon
														className={styles.icon}
														icon={faMoneyBillTransfer}
														styles={{ fontSize: "10", color: "black" }}
													/>
													Employee Transfer
												</a>
											</li>
											<li>
												<a href="#">
													<FontAwesomeIcon
														className={styles.icon}
														icon={faBuilding}
														styles={{ fontSize: "10", color: "black" }}
													/>
													Company Setting
												</a>
											</li>
										</ul>
									</div>

									<div>
										<h5 className={`border-bottom`}>Application</h5>
										<ul>
											<li>
												<a href="#">
													<FontAwesomeIcon
														className={styles.icon}
														icon={faSignal}
														styles={{ fontSize: "10", color: "black" }}
													/>
													Performance Review
												</a>
											</li>
										</ul>
									</div>

									<div>
										<h5 className={`border-bottom`}>Download EZHL</h5>
										<ul>
											<li>
												<a href="#">
													<FontAwesomeIcon
														className={styles.icon}
														icon={faA}
														styles={{ fontSize: "10", color: "black" }}
													/>
													App Store
												</a>
											</li>
											<li>
												<a href="#">
													<FontAwesomeIcon
														className={styles.icon}
														icon={faCaretRight}
														styles={{ fontSize: "10", color: "black" }}
													/>
													Google Play
												</a>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="card mb-2">
								<div class="card-body">
									<h3 class="card-title">Card title</h3>
									<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
									<p class="card-text">
										Some quick example text to build on the card title and make up the
										bulk of the card's content.
									</p>
									<a href="#" class="card-link">
										Card link
									</a>
									<a href="#" class="card-link">
										Another link
									</a>
								</div>
							</div>
							<div class="card mb-2">
								<div class="card-body">
									<h3 class="card-title">Card title</h3>
									<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
									<p class="card-text">
										Some quick example text to build on the card title and make up the
										bulk of the card's content.
									</p>
									<a href="#" class="card-link">
										Card link
									</a>
									<a href="#" class="card-link">
										Another link
									</a>
								</div>
							</div>
						</div>

						<div className={`${styles["card-row-three"]}`}>
							<div class="card mb-2">
								<div class="card-body">
									<div
										className={`${styles["card-title"]} d-flex justify-content-between`}
									>
										<h3 class="card-title">Job Level</h3>
										<FontAwesomeIcon icon={faEllipsisVertical} />
									</div>
									<div className={`${styles["progress-bar"]} progress`}>
										<div
											className={`${styles["progress1"]} progress-bar`}
											role="progressbar"
											aria-label="Segment one"
											aria-valuenow="15"
											aria-valuemin="0"
											aria-valuemax="100"
										></div>
										<div
											className={`${styles["progress2"]} progress-bar`}
											role="progressbar"
											aria-label="Segment two"
											aria-valuenow="30"
											aria-valuemin="0"
											aria-valuemax="100"
										></div>
										<div
											className={`${styles["progress3"]} progress-bar`}
											role="progressbar"
											aria-label="Segment three"
											aria-valuenow="20"
											aria-valuemin="0"
											aria-valuemax="100"
										></div>
									</div>
								</div>
							</div>
							<div class="card">
								<div class="card-body">
									<div
										className={`${styles["card-title"]} d-flex justify-content-between`}
									>
										<h3 class="card-title">Length Of Service </h3>
										<FontAwesomeIcon icon={faEllipsisVertical} />
									</div>
									<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
									<p class="card-text">
										Some quick example text to build on the card title and make up the
										bulk of the card's content.
									</p>
									<a href="#" class="card-link">
										Card link
									</a>
									<a href="#" class="card-link">
										Another link
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}

export async function getServerSideProps(){

	let headers = new Headers();

	headers.append("Content-Type", "application/json");
	headers.append("Accept", "application/json");
	// headers.append('Authorization', 'Basic ' + base64.encode(username + ":" +  password));
	headers.append("Origin", "http://localhost:3000");
	var bearer= "Bearer "
	var accessToken= "a"
	headers.append("Authorization", bearer+accessToken)

	// const res = await 
	const user = await fetch("http://localhost:3000/users/myprofile", {
	  mode: "cors",
	  credentials: "include",
	  method: "GET",
	  headers: headers,
	})

	const result = await user.json()
	return {
	  props : {
		user : result,
	 
	  }
	}
  }
