import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useState } from "react";
// import axios from "axios";

export default function Login() {
  const [userInput, setUserInput] = useState({});

  async function Signin(e) {
    e.preventDefault();
    

    let headers = new Headers();

    headers.append("Content-Type", "application/json");
    headers.append("Accept", "application/json");
    // headers.append('Authorization', 'Basic ' + base64.encode(username + ":" +  password));
    headers.append("Origin", "http://localhost:3000");

    // console.log(userInput)
    const res = await fetch("http://localhost:3000/auth/signin", {
      mode: "cors",
      credentials: "include",
      method: "POST",
      headers: headers,
      body: JSON.stringify(userInput),
    })
    var access_token = await res.json()

    sessionStorage.setItem("access_token", access_token.access_token)
    const temp = sessionStorage.getItem("access_token")
    if(res.ok){
      window.alert(temp)
      window.location.href = ("/dashboard")

    }else{
      console.log("sus")
      window.location.href = ("/Component/errorMessage")
      
    }
    }





  return (
    <div className={styles.container}>

      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.signIn}>
            <div className={styles.logo}>
              <Image
                src="/EasyHandler_Putih.png"
                alt="logo"
                width={200}
                height={200}
              />
            </div>
            <h2>Login To Your Account</h2>
            <div className={styles.formLogin}>
              <label>Email</label>
              <input value={userInput.email} onChange={e => setUserInput({...userInput, email: e.target.value})} name="email" type="email"></input>
            </div>

            <div className={styles.formLogin}>
              <label>Password</label>
              <input value={userInput.password} onChange={e => setUserInput({...userInput, password: e.target.value})} name="password" type="password"></input>
            </div>
            <Link href="/Registration/forgot">
            <a className={styles.forgot}>
              Forgot Password?
            </a>
            </Link>
            <button onClick={Signin} >
            <Link href="">
            <a className={styles.butSignin}>
              Sign In
            </a>
            </Link>
            </button>
          </div>
          <div className={styles.signUp}>
            <h1>New Here?</h1>
            <p>Sign up and discover a great amount of new opportunities</p>
            <Link href="/Registration/signUp">
              <a className={styles.butSignup}>Sign Up</a>
            </Link>
          </div>
        </div>
      </main>


    </div>
    
  );
}
